CREATE TABLE COMPRA (
    CD_COMPRA NUMBER(4) PRIMARY KEY , 
    DT_COMPRA DATE 
    );
    
CREATE TABLE  TIPO_PROD (
    CD_TIPO NUMBER(4) PRIMARY KEY ,
    NM_TIPO VARCHAR(40) NOT NULL
    );
    
CREATE TABLE PRODUTO(
    CD_PROD NUMBER(6) PRIMARY KEY ,
    NM_PROD VARCHAR(40) NOT NULL,
    FK_TIPO_PROD_CD_TIPO NUMBER(4) REFERENCES TIPO_PROD
    );

CREATE TABLE COMP_PROD_TEM(
    FK_COMPRA_CD_COMPRA NUMBER(4) CONSTRAINT COMPRA_CD_COMPRA REFERENCES COMPRA,
    FK_PROD_CD_PROD NUMBER(4) CONSTRAINT PROD_CD_PROD REFERENCES PRODUTO
    );
    