CREATE TABLE TBL_CONTATO(
    ID_CONTATO NUMERIC(4) PRIMARY KEY,
    NOME_CONTATO VARCHAR2(50) NOT NULL,
    CELULAR_CONTATO VARCHAR2(11) NOT NULL,
    EMAIL_CONTATO VARCHAR2(60) NOT NULL,
    INSTAGRAM VARCHAR2(50),
    TIPO VARCHAR2(20)
);

INSERT 
INTO TBL_CONTATO 
    (ID_CONTATO ,NOME_CONTATO ,CELULAR_CONTATO , EMAIL_CONTATO ,INSTAGRAM  , TIPO) 
VALUES
(2 , 
'Luiz Eduardo' , 
'981813016' , 
'Ledu64817@gmail' , 
'Lu1zEduu' , 
'Aluno' 
);
